// English translations, keyed by the French source copy. Arguments use {0}, {1}, …
import Foundation

enum EnglishStrings {
    static let values: [String: String] = [
        "Répartition du stockage": "Storage breakdown",
        "Documents des applications": "Application documents",
        "Photos": "Photos",
        "Section": "Section",
        "Répartition": "Breakdown",
        "Mémoire flash": "Flash storage",
        "Caractéristiques techniques": "Technical specifications",
        "Fournisseur": "Manufacturer",
        "Type de stockage": "Storage type",
        "Modèle de stockage": "Storage model",
        "Modèle de puce": "Chip model",
        "Version du micrologiciel": "Firmware version",
        "Nom de la mémoire NAND": "NAND flash name",
        "Version MSP": "MSP version",
        "Interface": "Interface",
        "Révision NVMe": "NVMe revision",
        "Lecture maximale par transfert": "Maximum read per transfer",
        "Écriture maximale par transfert": "Maximum write per transfer",
        "Segment maximal en lecture": "Maximum read segment",
        "Segment maximal en écriture": "Maximum write segment",
        "Nombre maximal de segments lus": "Maximum read segment count",
        "Nombre maximal de segments écrits": "Maximum write segment count",
        "Alignement minimal": "Minimum alignment",
        "Seuil de saturation": "Saturation threshold",
        "Taille d’entrée/sortie préférée": "Preferred I/O size",
        "Lecture des catégories et de la mémoire…": "Reading categories and flash storage…",
        "{0} octets": "{0} bytes",
        "Fond d’écran lu sur l’appareil · horloge synchronisée. La disposition est une illustration, pas une capture de l’écran verrouillé.": "Wallpaper read from the device · synchronized clock. This layout is an illustration, not a lock screen capture.",
        "Illustration du modèle · fond personnel indisponible par USB pour le moment.": "Model illustration · personal wallpaper currently unavailable over USB.",
        "Compte Apple (masqué)": "Apple Account (masked)",
        "Charge actuelle mesurée": "Measured current charge",
        "Capacité de conception": "Design capacity",
        "Capacité à pleine charge": "Full charge capacity",
        "Intensité instantanée": "Instantaneous current",
        "Tension": "Voltage",
        "Puissance calculée": "Calculated power",
        "Niveau critique": "Critical level",
        "Batterie sur alimentation interne": "Running on battery",
        "État de charge non exposé": "Charging state unavailable",
        "À comparer avec Réglages > Batterie sur l’appareil. Le niveau de charge ne mesure pas la santé de la batterie.": "Compare with Settings > Battery on the device. Charge level does not measure battery health.",
        "Données techniques": "Technical data",
        "Une mesure absente reste non exposée. Ces informations ne certifient pas l’origine de la batterie.": "Missing measurements remain unavailable. This information does not certify battery origin.",
        "Mises à jour continues": "Continuous updates",
        "Toutes les 15 s": "Every 15 seconds",
        "Les numéros de série ne sont pas inclus dans cet export.": "Serial numbers are not included in this export.",
        "Photothèque": "Photo library",
        "Photos et vidéos de la caméra": "Camera photos and videos",
        "Applications": "Applications",
        "Calendriers": "Calendars",
        "Notes": "Notes",
        "Messagerie vocale": "Voicemail",
        "Espace utilisé": "Used space",
        "Autres données": "Other data",
        "Répartition communiquée par l’appareil. Les catégories absentes restent regroupées dans l’espace utilisé.": "Breakdown reported by the device. Unavailable categories remain grouped within used space.",
        "Espace purgeable": "Purgeable space",
        "L’espace purgeable ne peut pas être déduit de l’espace libre. Consultez les réglages de stockage sur l’appareil pour les catégories non communiquées.": "Purgeable space cannot be inferred from free space. Check storage settings on the device for categories that are not reported.",
        "utilisés": "used",
        "Afficher les détails du stockage": "Show storage details",
        "Afficher les détails de la batterie": "Show battery details",
        "Fermer la fiche de l’appareil": "Close device information",
        "Dernière lecture : {0}": "Last read: {0}",
        "Informations disponibles à la connexion": "Information available at connection time",
        "Appareil déconnecté · dernières informations disponibles": "Device disconnected · last available information",
        "Actions rapides": "Quick actions",
        "Déconnecté": "Disconnected",
        "Réduire": "Show less",
        "Nom": "Name",
        "Numéro de téléphone": "Phone number",
        "Numéro de téléphone 2": "Phone number 2",
        "Opérateur": "Carrier",
        "Compte Apple": "Apple account",
        "Identifiant du modèle": "Model identifier",
        "Seules les informations communiquées par l’appareil sont affichées.": "Only information reported by the device is displayed.",
        "Stockage": "Storage",
        "{0} utilisés sur {1}": "{0} used of {1}",
        "{0} disponibles": "{0} available",
        "Espace disponible non communiqué": "Available space not reported",

        "Pause indisponible pendant la restauration": "Pause unavailable during restoration",
        "L’écriture du firmware doit se poursuivre sans interruption.": "Firmware writing must continue without interruption.",
        " Sous le seuil indicatif de 80 %, comparez la valeur sur l’appareil et faites examiner la batterie.": " Below the indicative 80% threshold, compare the device's reading and have the battery examined.",
        " Sous le seuil indicatif de 80 %, faites examiner la batterie. Ce signal n’est pas une certification de son état.": " Below the indicative 80% threshold, have the battery examined. This is not a certification of its condition.",
        "1 appareil détecté": "1 device detected",
        "Activation et sécurité": "Activation and security",
        "Activité": "Activity",
        "Activité et assistance": "Activity and support",
        "Activé": "Activated",
        "Actualisation…": "Refreshing…",
        "Actualiser": "Refresh",
        "Actualiser le catalogue": "Refresh catalogue",
        "Actualiser les appareils": "Refresh devices",
        "Actualiser les appareils (⌘R)": "Refresh devices (⌘R)",
        "Actualiser les sauvegardes": "Refresh backups",
        "Actualiser les versions et leur état de signature": "Refresh versions and signing status",
        "Actualisé à {0}. {1} {2}.": "Updated at {0}. {1} {2}.",
        "Adresse Bluetooth": "Bluetooth address",
        "Adresse Wi-Fi": "Wi-Fi address",
        "Adresse fictive. Sa lecture ne teste pas la qualité du réseau.": "Sample address. Reading it does not test network quality.",
        "Afficher dans le Finder": "Show in Finder",
        "Afficher la sauvegarde dans le Finder": "Show backup in Finder",
        "Afficher les numéros de série": "Show serial numbers",
        "Afficher les numéros de série dans les rapports et leurs exports": "Show serial numbers in reports and exports",
        "Aide Apple": "Apple help",
        "Ajouter": "Add",
        "Ajouter des sauvegardes locales": "Add local backups",
        "Ajouter un dossier…": "Add a folder…",
        "Ajouter une référence de comparaison": "Add a comparison reference",
        "Analyse du firmware…": "Inspecting firmware…",
        "Analyser l’IPSW": "Inspect IPSW",
        "Annulation demandée…": "Cancellation requested…",
        "Annulation…": "Cancelling…",
        "Annuler": "Cancel",
        "Annuler et supprimer le téléchargement partiel": "Cancel and delete partial download",
        "Aperçu actif": "Preview active",
        "Aperçu de l’interface": "Interface preview",
        "Aperçu · données fictives · opérations sur les appareils désactivées": "Preview · sample data · device operations disabled",
        "Appareil": "Device",
        "Appareil connecté": "Device connected",
        "Appareil d’exemple": "Sample device",
        "Appareil repéré en USB, accès indisponible": "USB device detected, access unavailable",
        "Appareils connectés": "Connected devices",
        "Apparence": "Appearance",
        "Apple Vision Pro · visionOS": "Apple Vision Pro · visionOS",
        "AppleDB (bêtas et archives)": "AppleDB (betas and archives)",
        "Application au repos": "App idle",
        "Application ouverte": "App opened",
        "Arrêter la vérification du fichier": "Stop file verification",
        "Au moins une source nécessaire a échoué. Vérifiez la connexion, déverrouillez l’appareil et relancez le Check. ": "At least one required source failed. Check the connection, unlock the device and run the Check again. ",
        "Aucun": "None",
        "Aucun appareil détecté": "No device detected",
        "Aucun appareil identifié. Gardez le câble branché, vérifiez l’écran de l’appareil et réessayez. La restauration reste bloquée.": "No device identified. Keep the cable connected, check the device screen and try again. Restoration remains blocked.",
        "Aucun appareil sélectionné": "No device selected",
        "Aucun modèle ne correspond à votre recherche.": "No models match your search.",
        "Aucun nouveau téléchargement. ": "No new download. ",
        "Aucune": "None",
        "Aucune liaison USB détectée": "No USB connection detected",
        "Aucune restauration lancée.": "No restore started.",
        "Aucune restauration ne sera relancée automatiquement. Gardez l’appareil connecté et actualisez son état.": "No restore will restart automatically. Keep the device connected and refresh its status.",
        "Aucune référence disponible": "No reference available",
        "Aucune référence d’usine indépendante. Une série lue ne prouve pas l’authenticité.": "No independent factory reference. Reading a serial number does not prove authenticity.",
        "Aucune sauvegarde Apple lisible dans ce dossier. Sélectionnez le dossier contenant Info.plist, Manifest.plist et Status.plist, ou son dossier parent.": "No readable Apple backup in this folder. Select the folder containing Info.plist, Manifest.plist and Status.plist, or its parent folder.",
        "Aucune version pour ces filtres": "No versions match these filters",
        "Authenticité des pièces": "Parts authenticity",
        "Autorisez la connexion sur l’iPhone": "Allow the connection on your iPhone",
        "Autre fichier…": "Another file…",
        "Avec Apple Configurator": "With Apple Configurator",
        "Batterie": "Battery",
        "Batterie en charge": "Battery charging",
        "Bienvenue dans ReWork": "Welcome to ReWork",
        "Build du système": "System build",
        "BuildManifest.plist est incomplet : version, modèles ou identités manquants.": "BuildManifest.plist is incomplete: missing version, models or identities.",
        "Bêtas": "Betas",
        "Capacité de stockage": "Storage capacity",
        "Capacité estimée": "Estimated capacity",
        "Capacité lue dans le domaine com.apple.disk_usage ; elle peut différer de la capacité commerciale.": "Capacity read from com.apple.disk_usage; it may differ from the advertised capacity.",
        "Capacité maximale": "Maximum capacity",
        "Capacité maximale déclarée": "Reported maximum capacity",
        "Capacité maximale estimée": "Estimated maximum capacity",
        "Carte matérielle": "Hardware board",
        "Catalogue indisponible": "Catalogue unavailable",
        "Ce Check servira de relevé de comparaison pour cet appareil. Il ne constitue pas une référence d’usine.": "This Check will be used as a comparison baseline for this device. It is not a factory reference.",
        "Ce choix est mémorisé après fermeture et appliqué dans Restaurer. Vous pouvez le modifier dans Restaurer pour la session en cours.": "This choice is saved after closing and applied in Restore. You can change it in Restore for the current session.",
        "Ce contrôle est le relevé initial. Relancez le Check pour effectuer une nouvelle comparaison.": "This check is the initial reading. Run the Check again to make a new comparison.",
        "Ce fichier ne contient pas de référence ReWork valide et exploitable.": "This file does not contain a valid usable ReWork reference.",
        "Ce firmware ne contient aucune identité complète de restauration ou de mise à jour.": "This firmware has no complete restore or update identity.",
        "Ce firmware ne correspond pas à l’appareil": "This firmware does not match the device",
        "Ce moteur est trop ancien pour imposer la conservation des données. Mettez idevicerestore à jour.": "This engine is too old to enforce data preservation. Update idevicerestore.",
        "Ce rapport est masqué. Exportez-le avec « Afficher les numéros de série » activé pour pouvoir le comparer.": "This report is redacted. Export it with Show serial numbers enabled to compare it.",
        "Ce rapport reste sur votre Mac. Il contient la version de ReWork, macOS, le modèle d’appareil et l’étape concernée. Les identifiants, chemins et journaux bruts sont exclus.": "This report stays on your Mac. It contains the ReWork version, macOS version, device model and relevant step. Identifiers, paths and raw logs are excluded.",
        "Cet IPSW ne permet pas de conserver les données de cet appareil.": "This IPSW does not support keeping data on this device.",
        "Cette donnée brute peut regrouper plusieurs champs séparés par +. Elle est conservée entière, sans en déduire arbitrairement un numéro de série court.": "This raw value may combine several fields separated by +. It is kept intact without guessing a short serial number.",
        "Cette référence appartient à un autre appareil ou à un exemple. Elle n’a pas été appliquée.": "This reference belongs to another device or a sample. It was not applied.",
        "Cette sauvegarde est incomplète. Elle ne peut pas être restaurée.": "This backup is incomplete and cannot be restored.",
        "Changer…": "Change…",
        "Chaque sauvegarde est conservée séparément. Vos anciennes copies restent disponibles.": "Each backup is stored separately. Your older copies remain available.",
        "Charge actuelle": "Current charge",
        "Chargement des modèles…": "Loading models…",
        "Chargement des versions…": "Loading versions…",
        "Chargement du catalogue…": "Loading catalogue…",
        "Check enregistré sur ce Mac": "Check saved on this Mac",
        "Chiffrement déjà activé sur cet appareil": "Encryption already enabled on this device",
        "Chiffrer la sauvegarde": "Encrypt backup",
        "Chiffrée": "Encrypted",
        "Choisir": "Choose",
        "Choisir l’IPSW": "Choose IPSW",
        "Choisir l’appareil": "Choose device",
        "Choisir un IPSW…": "Choose an IPSW…",
        "Choisir un firmware IPSW": "Choose IPSW firmware",
        "Choisir une version": "Choose a version",
        "Choisir une version…": "Choose a version…",
        "Choisissez Toutes ou désactivez le filtre Signées uniquement. Certains anciens fichiers ne sont plus disponibles chez Apple.": "Choose All or turn off Signed only. Some older files are no longer available from Apple.",
        "Choisissez le thème sombre, clair ou système et votre langue dans Configuration. ReWork est un projet libre, sans abonnement, conçu pour vous laisser la main sur vos appareils. Cette visite reste accessible dans les réglages.": "Choose dark, light or system appearance and your language in Settings. ReWork is a free project without a subscription, designed to keep you in control of your devices. You can replay this tour in Settings.",
        "Choisissez un dossier accessible pour enregistrer le fichier IPSW.": "Choose an accessible folder to save the IPSW file.",
        "Choisissez un modèle": "Choose a model",
        "Choisissez un mot de passe pour activer le chiffrement.": "Choose a password to enable encryption.",
        "Choisissez un rapport JSON du même appareil, exporté avec les numéros de série visibles.": "Choose a JSON report from the same device, exported with serial numbers visible.",
        "Choisissez une sauvegarde de la même famille d’appareils.": "Choose a backup from the same device family.",
        "Choisissez une version d’iOS ou d’iPadOS, ou utilisez votre fichier IPSW.": "Choose an iOS or iPadOS version, or use your IPSW file.",
        "Choisissez une version à télécharger depuis Apple,\nou utilisez un fichier IPSW déjà sur votre Mac.": "Choose a version to download from Apple,\nor use an IPSW file already on your Mac.",
        "Choisissez une version, ou utilisez votre fichier IPSW.": "Choose a version, or use your IPSW file.",
        "Choisissez votre appareil Apple.": "Choose your Apple device.",
        "Choisissez votre firmware dans le catalogue. ReWork vérifie les IPSW déjà présents, télécharge depuis Apple et permet de mettre le téléchargement en pause. Choisissez ensuite de conserver les données ou d’effacer l’appareil avant confirmation.": "Choose firmware from the catalogue. ReWork checks existing IPSWs, downloads from Apple and lets you pause downloads. Then choose to keep data or erase the device before confirming.",
        "Cible ou chemin IPSW non valide.": "Invalid target or IPSW path.",
        "Clair": "Light",
        "Commencer la visite": "Start tour",
        "Comparé": "Compared",
        "Compris": "Got it",
        "Compteur déclaré par la batterie lorsqu’il est exposé ; il ne prouve pas son authenticité.": "Cycle count reported by the battery when exposed; it does not prove authenticity.",
        "Configuration": "Settings",
        "Configuration…": "Settings…",
        "Confirmer": "Confirm",
        "Confirmer le mot de passe": "Confirm password",
        "Confirmez le chiffrement sur l’appareil": "Confirm encryption on the device",
        "Confirmez le code demandé sur l’appareil et gardez le câble branché.": "Confirm the code requested on the device and keep the cable connected.",
        "Connecter": "Connect",
        "Connectez et déverrouillez l’appareil en mode normal.": "Connect and unlock the device in normal mode.",
        "Connectez un appareil pour continuer.": "Connect a device to continue.",
        "Connectez un appareil pour vérifier la compatibilité": "Connect a device to check compatibility",
        "Connectez votre appareil en USB pour lire son identité,\nsa batterie et les informations accessibles.": "Connect your device via USB to read its identity,\nbattery and accessible information.",
        "Connectez votre appareil en USB.": "Connect your device via USB.",
        "Connectez votre iPhone ou iPad": "Connect your iPhone or iPad",
        "Connectez votre iPhone ou iPad avec un câble USB, déverrouillez-le et acceptez Faire confiance. Découvrez les fonctions de ReWork en quelques étapes.": "Connect your iPhone or iPad using a USB cable, unlock it and accept Trust. Discover ReWork in a few steps.",
        "Connectez votre iPhone ou iPad, puis cliquez sur Sauvegarder. Vous pouvez aussi ajouter le dossier d’une sauvegarde Finder existante.": "Connect your iPhone or iPad, then click Back Up. You can also add an existing Finder backup folder.",
        "Connectivité": "Connectivity",
        "Connecté": "Connected",
        "Connexion à vérifier": "Check the connection",
        "Conservation des données": "Keep user data",
        "Conservation des données proposée. Une sauvegarde récente reste nécessaire.": "Data preservation selected. A recent backup is still needed.",
        "Conserver les données": "Keep user data",
        "Conserver les données de l’iPhone ou de l’iPad": "Keep data on the iPhone or iPad",
        "Consultation de ReWork": "Browsing ReWork",
        "Consulter les contrôles": "View checks",
        "Consultez Réglages → Général → Informations → Historique des pièces et des réparations, si disponible.": "Check Settings → General → About → Parts and Service History, if available.",
        "Consultez le journal, puis vérifiez le câble et le firmware avant un nouvel essai.": "Review the log, then check the cable and firmware before trying again.",
        "Contenu exact du rapport": "Exact report contents",
        "Continuer": "Continue",
        "Continuer…": "Continue…",
        "Contrôle de l’intégrité et de la compatibilité…": "Checking integrity and compatibility…",
        "Contrôle partiel · {0}": "Partial check · {0}",
        "Conçue en Belgique 🇧🇪": "Designed in Belgium 🇧🇪",
        "Copier": "Copy",
        "Copier la valeur complète : ": "Copy full value: ",
        "Copié": "Copied",
        "Couleur déclarée": "Reported colour",
        "Créez une sauvegarde, choisissez son emplacement et consultez celles déjà disponibles. Le chiffrement protège vos données : conservez précieusement votre mot de passe.": "Create a backup, choose its location and browse existing copies. Encryption protects your data: keep your password safe.",
        "Créé automatiquement au premier téléchargement. Aucun choix de dossier à chaque fois.": "Created automatically on the first download. No need to choose a folder each time.",
        "Cycles de charge": "Charge cycles",
        "C’est parti": "Let's go",
        "Dans Configurator, sélectionnez le casque puis Actions > Avancées > Restaurer.": "In Configurator, select the headset, then Actions > Advanced > Restore.",
        "Depuis Apple · {0}": "From Apple · {0}",
        "Depuis les serveurs Apple": "From Apple servers",
        "Dernière vérification SHA-256": "Final SHA-256 verification",
        "Des données lisibles. Des limites transparentes.": "Readable data. Transparent limitations.",
        "Description du problème": "Problem description",
        "Diagnostic de la batterie": "Battery diagnostics",
        "Disponible": "Available",
        "Domaine batterie": "Battery domain",
        "Données disponibles": "Available readings",
        "Données fictives. Les opérations sur les appareils sont désactivées.": "Sample data. Device operations are disabled.",
        "Données restaurées · l’appareil peut redémarrer": "Data restored · the device may restart",
        "Dossier de téléchargement des IPSW": "IPSW download folder",
        "Dossier des fichiers IPSW": "IPSW files folder",
        "Délai de lecture dépassé. Vérifiez le câble, déverrouillez l’appareil et relancez le Check.": "Reading timed out. Check the cable, unlock the device and run the Check again.",
        "Démarrage de la restauration avec effacement": "Starting restore with erase",
        "Déposez votre fichier IPSW.": "Drop your IPSW file here.",
        "Détails : ": "Details: ",
        "Détection USB": "USB detection",
        "Détection de l’appareil": "Detecting device",
        "Détection de l’appareil…": "Detecting device…",
        "Détection récupération / DFU": "Recovery / DFU detection",
        "Déverrouillez l’appareil en mode normal pour vérifier sa version avant de conserver les données.": "Unlock the device in normal mode to verify its version before keeping data.",
        "Déverrouillez l’appareil et acceptez « Faire confiance » avant de réessayer.": "Unlock the device and accept Trust before trying again.",
        "Déverrouillez votre appareil": "Unlock your device",
        "Effacement complet": "Erase all data",
        "Effacement complet proposé. Toutes les données seront supprimées si vous confirmez la restauration.": "Full erase selected. All data will be deleted if you confirm the restore.",
        "Effacer et restaurer": "Erase and restore",
        "Effacer et restaurer cet appareil ?": "Erase and restore this device?",
        "Emplacement des nouvelles sauvegardes": "Location for new backups",
        "Empreinte SHA-256": "SHA-256 fingerprint",
        "En USB sur votre Mac": "Via USB on your Mac",
        "En attente d’un appareil": "Waiting for a device",
        "Enregistrer": "Save",
        "Enregistrer ce Check": "Save this Check",
        "Enregistrez ce Check ou importez un ancien rapport du même appareil. Les références sont conservées sur ce Mac et rechargées aux prochains contrôles. Les mesures évolutives et tests manuels ne sont pas comparés. L’origine usine des pièces n’est pas certifiée.": "Save this Check or import an older report from the same device. References are kept on this Mac and reloaded for later checks. Changing measurements and manual tests are not compared. The factory origin of parts is not certified.",
        "Envoi des images de restauration": "Sending restore images",
        "Envoi du système de fichiers": "Sending file system",
        "Envoyer": "Send",
        "Envoyer…": "Send…",
        "Estimation à partir de NominalChargeCapacity / DesignCapacity. Ce calcul ne remplace pas l’état de santé affiché par iOS.": "Estimated from NominalChargeCapacity / DesignCapacity. This calculation does not replace the health status shown by iOS.",
        "Exemple": "Sample",
        "Exemple de compteur de cycles communiqué par l’appareil.": "Example cycle count reported by the device.",
        "Exemple de valeur retournée par ideviceinfo. Sans référence d’usine.": "Example value returned by ideviceinfo. No factory reference.",
        "Exemple d’estimation inférieure à 80 %. Ce résultat invite à examiner la batterie; il ne certifie pas l’origine de la pièce.": "Example estimate below 80%. This result suggests examining the battery; it does not certify the part's origin.",
        "Explorer avec un appareil d’exemple": "Explore with a sample device",
        "Explorer l’interface": "Explore the interface",
        "Exporter": "Export",
        "Exporter avec les identifiants": "Export with identifiers",
        "Exporter le rapport": "Export report",
        "Exporter le rapport d’incident": "Export incident report",
        "Exporter le rapport masqué": "Export redacted report",
        "Exporter…": "Export…",
        "Face ID / Touch ID": "Face ID / Touch ID",
        "Faites le point sur son identité, sa batterie et les données accessibles.": "Review its identity, battery and accessible data.",
        "Famille": "Family",
        "Famille d’appareils": "Device family",
        "Fermer": "Close",
        "Fermer la configuration": "Close settings",
        "Fermer la sélection": "Close selection",
        "Fermer la visite": "Close tour",
        "Fermer le catalogue": "Close catalogue",
        "Fermer le détail": "Close details",
        "Fermer le rapport": "Close report",
        "Fichier local…": "Local file…",
        "Firmware IPSW": "IPSW firmware",
        "Firmware compatible avec cet appareil": "Firmware compatible with this device",
        "Firmware vérifié": "Firmware verified",
        "Garder une copie": "Keep a copy",
        "Gardez ReWork ouvert et l’appareil connecté jusqu’à la fin de l’opération.": "Keep ReWork open and the device connected until the operation finishes.",
        "Gardez le câble connecté jusqu’à la fin. L’appareil pourra redémarrer et demander votre compte Apple. Si iOS le demande, désactivez Localiser dans ses réglages.": "Keep the cable connected until completion. The device may restart and request your Apple account. If iOS asks, turn off Find My in Settings.",
        "Gardez le fil": "Keep track",
        "Gardez l’appareil connecté. Cette opération peut prendre plusieurs minutes.": "Keep the device connected. This may take several minutes.",
        "Guide de restauration Vision Pro": "Vision Pro restore guide",
        "IPSW analysé": "IPSW inspected",
        "IPSW existant réutilisé": "Existing IPSW reused",
        "IPSW local vérifié et réutilisé": "Local IPSW verified and reused",
        "IPSW téléchargé": "IPSW downloaded",
        "IPSW téléchargé et vérifié": "IPSW downloaded and verified",
        "IPSW vérifié": "Verified IPSW",
        "IPSW.me + AppleDB · actualisé {0}": "IPSW.me + AppleDB · updated {0}",
        "Identifiant USB non valide.": "Invalid USB identifier.",
        "Identifiant de la dalle (brut)": "Panel identifier (raw)",
        "Identifiant de la vitre": "Cover glass identifier",
        "Identifiant déclaré par l’appareil. Aucune référence d’usine indépendante n’est disponible. ": "Identifier reported by the device. No independent factory reference is available. ",
        "Identifiant fictif utilisé uniquement pour cet aperçu.": "Sample identifier used only for this preview.",
        "Identifiant fictif, masqué par défaut.": "Sample identifier, hidden by default.",
        "Identique": "Identical",
        "Identité": "Identity",
        "Identité de l’appareil": "Device identity",
        "Identité relue sur l’appareil sélectionné.": "Identity reread from the selected device.",
        "Illustration du modèle et de la finition déclarés par l’appareil. Écran illustratif.": "Illustration of the model and finish reported by the device. Illustrative screen.",
        "Illustration générique : modèle ou finition non disponible sur ce Mac.": "Generic illustration: model or finish unavailable on this Mac.",
        "Importer": "Import",
        "Importer un rapport ReWork comme référence": "Import a ReWork report as a reference",
        "Importer un rapport…": "Import a report…",
        "Impossible de lire BuildManifest.plist. Le fichier doit être une archive IPSW valide.": "Could not read BuildManifest.plist. The file must be a valid IPSW archive.",
        "Impossible de lire le chiffrement de l’appareil.": "Could not read device encryption status.",
        "Impossible de vérifier le chiffrement de l’appareil.": "Could not verify device encryption.",
        "Impossible d’enregistrer l’état de l’opération. {0}": "Could not save the operation state. {0}",
        "Inclus dans l’app": "Included in the app",
        "Inconnu": "Unknown",
        "Inconnue": "Unknown",
        "Indisponible": "Unavailable",
        "Informations de l’appareil": "Device information",
        "Informations générales · lockdown": "General information · lockdown",
        "Infos · À propos de ReWork": "Info · About ReWork",
        "Installation du firmware": "Installing firmware",
        "Installation du modem": "Installing modem",
        "Installez iOS/iPadOS {0} ou une version plus récente sur l’appareil.": "Install iOS/iPadOS {0} or later on the device.",
        "Intégrité du système": "System integrity",
        "Inventaire IOService": "IOService inventory",
        "Je confirme la cible et le remplacement de ses données.": "I confirm the target and replacement of its data.",
        "Je confirme la réinstallation et le risque de perte de données.": "I confirm reinstallation and the risk of data loss.",
        "Je confirme l’effacement de l’appareil sélectionné.": "I confirm erasing the selected device.",
        "Je dispose des identifiants Apple nécessaires à l’activation.": "I have the Apple account credentials required for activation.",
        "Journal de la dernière restauration": "Last restore log",
        "Journal de sécurité indisponible": "Safety journal unavailable",
        "Journal du moteur · peut contenir des informations techniques": "Engine log · may contain technical information",
        "J’ai sauvegardé mes données ou j’accepte de les perdre.": "I have backed up my data or accept losing it.",
        "J’ai une sauvegarde récente de mes données.": "I have a recent backup of my data.",
        "La bonne version, au bon endroit": "The right version, in the right place",
        "La charge actuelle est distincte de la santé de la batterie.": "Current charge is separate from battery health.",
        "La cible ou le dossier de sauvegarde n’est pas valide.": "The target or backup folder is invalid.",
        "La commande de lecture a échoué (code {0}). Vérifiez la connexion et l’autorisation Faire confiance.": "The read command failed (code {0}). Check the connection and Trust permission.",
        "La compatibilité locale ne garantit pas qu’Apple autorise encore cette version.": "Local compatibility does not guarantee that Apple still allows this version.",
        "La confirmation ne correspond plus à l’appareil ou au fichier sélectionné.": "The confirmation no longer matches the selected device or file.",
        "La connexion attend l’autorisation de cet ordinateur. Déverrouillez l’iPhone, acceptez « Faire confiance » et saisissez votre code sur l’appareil. La détection se relance automatiquement.": "The connection is waiting for this computer to be trusted. Unlock the iPhone, accept Trust and enter your passcode on the device. Detection retries automatically.",
        "La connexion avec l’appareil a été interrompue. Vérifiez la cible avant de confirmer à nouveau.": "The device connection was interrupted. Check the target before confirming again.",
        "La connexion n’a pas pu être établie. Déverrouillez l’appareil, vérifiez sa présence dans le Finder et relancez la détection.": "The connection could not be established. Unlock the device, check it appears in Finder and retry detection.",
        "La conservation des données exige la même version ou une version plus récente. Un retour en arrière est bloqué.": "Keeping data requires the same or a newer version. Downgrades are blocked.",
        "La copie a échoué. Réessayez.": "Copy failed. Try again.",
        "La lecture actuelle ne permet pas de comparer cette valeur.": "The current reading does not allow this value to be compared.",
        "La lecture d’un numéro de série ne certifie pas une pièce d’origine. Consultez Réglages > Général > Informations > Historique des pièces et des réparations, lorsque disponible.": "Reading a serial number does not certify an original part. Check Settings > General > About > Parts and Service History when available.",
        "La restauration directe et la sauvegarde locale de Vision Pro ne sont pas prises en charge par ReWork. Ne comptez pas sur une conservation des données lors de cette procédure.": "Direct Vision Pro restoration and local backups are not supported by ReWork. Do not rely on data preservation during this procedure.",
        "La restauration n’a pas abouti": "The restore did not complete",
        "La réponse de cette source n’a pas pu être interprétée. Relancez le Check.": "This source's response could not be interpreted. Run the Check again.",
        "La réponse du catalogue dépasse la taille autorisée.": "The catalogue response exceeds the allowed size.",
        "La réponse dépasse la limite de lecture autorisée.": "The response exceeds the allowed reading limit.",
        "La sauvegarde a changé depuis sa sélection.": "The backup changed after it was selected.",
        "La sauvegarde est incomplète.": "The backup is incomplete.",
        "La sauvegarde locale de Vision Pro n’est pas prise en charge. Utilisez les options iCloud du casque.": "Local Vision Pro backups are not supported. Use the headset's iCloud options.",
        "La sauvegarde ne contient pas les informations nécessaires.": "The backup lacks the required information.",
        "La sauvegarde n’a pas été confirmée comme complète.": "The backup was not confirmed as complete.",
        "La sortie de {0} dépasse la limite autorisée.": "Output from {0} exceeds the allowed limit.",
        "La valeur diffère du relevé de référence. Un écart ne prouve ni un remplacement ni une contrefaçon.": "The value differs from the reference. A difference proves neither replacement nor counterfeiting.",
        "La valeur est identique au relevé de référence ; cela ne certifie pas son origine.": "The value matches the reference; this does not certify its origin.",
        "La variante de mise à jour n’est pas vérifiée pour cet appareil.": "The update variant is not verified for this device.",
        "La version du système n’est pas vérifiable.": "The system version cannot be verified.",
        "La vérification nécessite un appareil démarré normalement, déverrouillé et approuvé sur ce Mac.": "Verification requires a normally booted, unlocked device that trusts this Mac.",
        "Laisser l’opération se terminer": "Let the operation finish",
        "Lancer la vérification": "Start verification",
        "Lancer un Check": "Run a Check",
        "Langue": "Language",
        "Le catalogue a renvoyé des métadonnées de firmware invalides.": "The catalogue returned invalid firmware metadata.",
        "Le catalogue n’est pas disponible.": "The catalogue is unavailable.",
        "Le chiffrement demandé n’est pas confirmé dans la sauvegarde.": "The requested encryption is not confirmed in the backup.",
        "Le chiffrement n’a pas été activé. Vérifiez le code demandé sur l’appareil.": "Encryption was not enabled. Check the code requested on the device.",
        "Le chiffrement protège aussi les données sensibles prises en charge, comme les mots de passe et Santé. S’il est déjà actif, le mot de passe existant est conservé.": "Encryption also protects supported sensitive data, such as passwords and Health data. If already enabled, the existing password is kept.",
        "Le contenu de l’IPSW ne correspond pas à la version choisie. Il ne sera pas proposé pour la restauration.": "The IPSW contents do not match the selected version. It will not be offered for restoration.",
        "Le disque est plein. Libérez de l’espace et recommencez la sauvegarde.": "The disk is full. Free some space and restart the backup.",
        "Le dossier de sauvegarde n’est pas valide ou contient un lien symbolique.": "The backup folder is invalid or contains a symbolic link.",
        "Le dossier des sauvegardes est inaccessible. Vérifiez son emplacement et ses autorisations.": "The backup folder is inaccessible. Check its location and permissions.",
        "Le dossier source n’est pas valide.": "The source folder is invalid.",
        "Le début d’une nouvelle session.": "The start of a new session.",
        "Le fichier IPSW a changé avant le démarrage du moteur.": "The IPSW file changed before the engine started.",
        "Le fichier IPSW a changé avant le lancement. Sélectionnez-le et confirmez à nouveau.": "The IPSW changed before starting. Select it and confirm again.",
        "Le fichier IPSW a changé ou sa compatibilité n’est plus vérifiable. Confirmez à nouveau la restauration.": "The IPSW changed or its compatibility can no longer be verified. Confirm the restore again.",
        "Le fichier IPSW a changé pendant sa vérification. Sélectionnez-le à nouveau.": "The IPSW file changed during verification. Select it again.",
        "Le fichier IPSW est vide, inaccessible ou n’est pas un fichier régulier.": "The IPSW file is empty, inaccessible or not a regular file.",
        "Le fichier reçu ne correspond pas à la taille annoncée. Le téléchargement incomplet a été supprimé.": "The received file does not match the expected size. The incomplete download was deleted.",
        "Le fichier sera proposé pour la restauration une fois validé.": "The file will be available for restoration once verified.",
        "Le fil de vos opérations, conservé pendant cette session.": "A timeline of your operations during this session.",
        "Le firmware ne correspond pas au modèle et à la carte matérielle de cet appareil.": "The firmware does not match this device's model and hardware board.",
        "Le firmware ou l’appareil a changé pendant les derniers contrôles.": "The firmware or device changed during the final checks.",
        "Le journal de restauration est trop volumineux.": "The restore log is too large.",
        "Le journal de sécurité est inaccessible. La restauration reste bloquée : {0}": "The safety journal is inaccessible. Restoration remains blocked: {0}",
        "Le journal de sécurité est trop volumineux.": "The safety journal is too large.",
        "Le lancement est désactivé dans l’aperçu.": "Starting operations is disabled in preview mode.",
        "Le mode de mise à jour sera imposé. Il ne garantit pas l’absence de perte de données : conservez une sauvegarde récente. En cas d’échec, l’opération s’arrête sans relance en mode effacement.": "Update mode will be enforced. Data preservation cannot be guaranteed: keep a recent backup. If the operation fails, it stops without retrying in erase mode.",
        "Le module de protection de la restauration est absent. Lancez le bundle ReWork complet.": "The restore protection module is missing. Launch the complete ReWork app bundle.",
        "Le modèle choisi diffère de l’appareil connecté. Connectez l’appareil correspondant avant de restaurer ce fichier.": "The selected model differs from the connected device. Connect the matching device before restoring this file.",
        "Le modèle de l’appareil n’a pas pu être lu. Déverrouillez-le et autorisez cet ordinateur.": "The device model could not be read. Unlock it and trust this computer.",
        "Le mot de passe de cette sauvegarde est nécessaire.": "This backup's password is required.",
        "Le mot de passe de la sauvegarde est incorrect.": "The backup password is incorrect.",
        "Le moteur a terminé sans erreur. Poursuivez la configuration sur l’appareil.": "The engine completed without errors. Continue setup on the device.",
        "Le moteur de connexion est incomplet": "Connection tools are incomplete",
        "Le moteur de lecture de l’appareil est indisponible.": "The device reading engine is unavailable.",
        "Le moteur de restauration doit être installé pour lancer l’opération.": "The restore engine must be installed to start the operation.",
        "Le moteur de restauration s’est arrêté sans résultat confirmé. Gardez l’appareil connecté et consultez le rapport d’incident.": "The restore engine stopped without a confirmed result. Keep the device connected and review the incident report.",
        "Le moteur indépendant reste actif. Gardez le câble branché.": "The independent engine is still running. Keep the cable connected.",
        "Le rapport distingue les données lues, les points à examiner\net les contrôles à effectuer directement sur votre appareil.": "The report distinguishes readings, items to review\nand checks to perform directly on your device.",
        "Le rapport indique les données accessibles et les contrôles indisponibles.": "The report shows accessible data and unavailable checks.",
        "Le serveur a répondu avec le code HTTP {0}. Réessayez plus tard.": "The server returned HTTP {0}. Try again later.",
        "Le service Apple indique que l’appareil est verrouillé. Déverrouillez-le et laissez son écran allumé pendant la connexion.": "The Apple service reports that the device is locked. Unlock it and keep its screen on while connecting.",
        "Le service a refusé ou échoué à exécuter la requête. Déverrouillez l’appareil et relancez le Check.": "The service refused or failed to run the request. Unlock the device and run the Check again.",
        "Le service de connexion ne répond pas": "Connection service not responding",
        "Le téléchargement doit rester sur un serveur Apple en HTTPS. Cette URL ou redirection a été refusée.": "Downloads must stay on Apple HTTPS servers. This URL or redirect was rejected.",
        "Le téléchargement est terminé.": "Download complete.",
        "Le téléchargement n’a pas abouti": "The download did not complete",
        "Le verrou de restauration est inaccessible.": "The restore lock is inaccessible.",
        "Lecture de l’appareil…": "Reading device…",
        "Lecture des informations de l’appareil": "Reading device information",
        "Lecture du chiffrement de l’appareil…": "Reading device encryption status…",
        "Lecture du manifeste et calcul SHA-256": "Reading manifest and computing SHA-256",
        "Lecture interrompue": "Reading interrupted",
        "Lecture locale. Les contrôles indisponibles ne valent pas validation. Aucune certification d’authenticité.": "Local readings. Unavailable checks do not count as validation. No authenticity certification.",
        "Lecture partielle · {0} source{1} à relancer": "Partial reading · {0} source{1} to retry",
        "Lecture terminée": "Reading complete",
        "Lecture échouée": "Read failed",
        "Les données absentes restent indiquées. Chaque contrôle précise ses limites.": "Missing data remains marked. Each check explains its limitations.",
        "Les données et réglages de la sauvegarde remplaceront ceux de l’appareil. La version d’iOS installée restera la même. Sauvegardez d’abord les données actuelles si vous souhaitez les conserver.": "The backup's data and settings will replace those on the device. The installed iOS version will remain unchanged. Back up current data first if you want to keep it.",
        "Les fichiers IPSW sont téléchargés depuis les serveurs Apple.": "IPSW files are downloaded from Apple servers.",
        "Les identifiants sont masqués dans l’export.": "Identifiers are hidden in the export.",
        "Les informations Recovery/DFU sont incomplètes. Mettez à jour libirecovery.": "Recovery/DFU information is incomplete. Update libirecovery.",
        "Les informations matérielles de l’appareil ont changé depuis la confirmation.": "The device hardware information has changed since confirmation.",
        "Les menus macOS suivent la langue choisie au prochain lancement.": "macOS menus use the selected language after the next launch.",
        "Les métadonnées ne peuvent pas être des liens symboliques.": "Metadata files cannot be symbolic links.",
        "Les numéros de série seront masqués": "Serial numbers will be hidden",
        "Les outils de détection USB, de diagnostic et de restauration IPSW sont inclus dans ReWork.": "USB detection, diagnostics and IPSW restore tools are included in ReWork.",
        "Les outils intégrés et les illustrations Apple conservent leurs licences et droits respectifs. ReWork n’est pas affilié à Apple.": "Bundled tools and Apple illustrations retain their respective licences and rights. ReWork is not affiliated with Apple.",
        "Les sources consultées n’exposent pas ce champ. Cela ne constitue pas un défaut de la pièce. ": "The queried sources do not expose this field. This does not indicate a faulty part. ",
        "Les sources renvoient des identifiants différents. Aucune valeur n’est retenue automatiquement ; cela ne prouve pas un remplacement.": "Sources return different identifiers. No value is selected automatically; this does not prove a replacement.",
        "Lire la procédure Apple": "Read Apple's procedure",
        "Lu": "Read",
        "L’ECID de l’appareil est nécessaire pour lui associer une référence.": "The device ECID is required to associate a reference with it.",
        "L’IPSW déjà présent est vérifié et réutilisé. Sinon, il est téléchargé avant confirmation.": "An existing IPSW is verified and reused. Otherwise, it is downloaded before confirmation.",
        "L’IPSW n’a pas pu être validé": "The IPSW could not be validated",
        "L’absence de jailbreak ne peut pas être certifiée à partir de ces lectures publiques.": "These public readings cannot certify the absence of a jailbreak.",
        "L’activation s’applique aux prochaines sauvegardes de cet appareil. Conservez ce mot de passe : ReWork ne l’enregistre pas et ne pourra pas le retrouver.": "Enabling encryption applies to future backups of this device. Keep this password: ReWork does not store it and cannot recover it.",
        "L’appareil a changé ou a été déconnecté pendant l’actualisation. Vérifiez la connexion et relancez le Check.": "The device changed or disconnected during refresh. Check the connection and run the Check again.",
        "L’appareil a changé ou a été déconnecté. Vérifiez la cible et confirmez à nouveau la restauration.": "The device has changed or disconnected. Check the target and confirm the restore again.",
        "L’appareil a changé. Sélectionnez à nouveau la sauvegarde et confirmez la cible.": "The device changed. Select the backup again and confirm the target.",
        "L’appareil confirmé doit être connecté et identifiable par un ECID unique. Rebranchez-le et recommencez.": "The confirmed device must be connected and identifiable by a unique ECID. Reconnect it and try again.",
        "L’appareil connecté a changé. Confirmez à nouveau la cible.": "The connected device changed. Confirm the target again.",
        "L’appareil connecté ne correspond plus à l’appareil sélectionné.": "The connected device no longer matches the selected device.",
        "L’appareil demande de désactiver Localiser avant la restauration. Vérifiez son écran.": "The device asks you to turn off Find My before restoring. Check its screen.",
        "L’appareil doit être connecté, déverrouillé et avoir accepté « Faire confiance ».": "The device must be connected, unlocked and have accepted “Trust”.",
        "L’appareil indique que cette requête n’est pas prise en charge.": "The device reports that this request is unsupported.",
        "L’appareil n’a pas confirmé la fin de l’opération. Vérifiez son écran, la connexion USB et le mot de passe éventuel. Un rapport d’incident est disponible.": "The device did not confirm completion. Check its screen, USB connection and password if applicable. An incident report is available.",
        "L’appareil sélectionné a changé pendant le téléchargement. Sélectionnez la bonne cible avant de préparer la restauration.": "The selected device changed during download. Select the correct target before preparing the restore.",
        "L’application reste ouverte pendant l’écriture du firmware.": "The app stays open while firmware is being written.",
        "L’empreinte SHA-256 ne correspond pas au catalogue. Le fichier a été supprimé.": "The SHA-256 fingerprint does not match the catalogue. The file was deleted.",
        "L’espace libre du dossier choisi est insuffisant pour ce fichier IPSW.": "The selected folder has insufficient free space for this IPSW file.",
        "L’espace libre est insuffisant pour démarrer une sauvegarde.": "Insufficient free space to start a backup.",
        "L’export contiendra les numéros de série": "The export will include serial numbers",
        "L’export inclut les identifiants affichés.": "The export includes the displayed identifiers.",
        "L’iPhone indique que la lecture MobileGestalt a été retirée. Les autres sources restent utilisées.": "The iPhone reports that MobileGestalt reading has been removed. Other sources are still used.",
        "L’identité ECID est indisponible. La restauration reste bloquée pour éviter de cibler le mauvais appareil.": "The ECID is unavailable. Restoration is blocked to avoid targeting the wrong device.",
        "L’opération a été interrompue. Vérifiez la connexion USB et l’espace libre, puis consultez le rapport.": "The operation was interrupted. Check the USB connection and free space, then review the report.",
        "L’opération s’est terminée avec succès.": "The operation completed successfully.",
        "L’outil de lecture est absent du bundle. Réinstallez ReWork.": "The reading tool is missing from the bundle. Reinstall ReWork.",
        "L’outil de restauration vérifie la signature Apple. La disponibilité d’un fichier IPSW ne garantit pas qu’Apple accepte encore cette version.": "The restore tool checks Apple signing. IPSW availability does not guarantee Apple still accepts this version.",
        "L’outil n’a pas renvoyé un dictionnaire plist valide.": "The tool did not return a valid plist dictionary.",
        "L’outil {0} est introuvable. Consultez les instructions d’installation.": "The {0} tool was not found. See the installation instructions.",
        "L’état d’activation actuel ne permet pas de conclure sur le verrouillage d’activation.": "Current activation status does not establish Activation Lock status.",
        "MODÈLE": "MODEL",
        "Masquer l’avis d’interruption": "Dismiss interruption notice",
        "Masqué": "Hidden",
        "Mes sauvegardes": "My backups",
        "Mise à jour des composants": "Updating components",
        "Mode DFU": "DFU mode",
        "Mode normal": "Normal mode",
        "Modifier…": "Change…",
        "Modèle": "Model",
        "Modèle : ": "Model: ",
        "Modèle identifié ; finition non disponible. Coque neutre, fond illustratif adapté au système.": "Model identified; finish unavailable. Neutral enclosure with a system-appropriate illustrative wallpaper.",
        "Modèle ou identifiant": "Model or identifier",
        "Modèles : {0}": "Models: {0}",
        "Mot de passe (pour activer le chiffrement)": "Password (to enable encryption)",
        "Mot de passe de la sauvegarde": "Backup password",
        "Moteur de restauration": "Restore engine",
        "Métadonnées de sauvegarde illisibles.": "Unreadable backup metadata.",
        "Méthode et limites": "Method and limitations",
        "Niveau de charge": "Charge level",
        "Niveau de charge instantané. Une charge à 0 % n’indique pas une capacité maximale à 0 %.": "Current charge level. A 0% charge does not mean 0% maximum capacity.",
        "Non": "No",
        "Non chiffrée": "Unencrypted",
        "Non comparable": "Not comparable",
        "Non disponible": "Unavailable",
        "Non exposé": "Not exposed",
        "Non lus / manuels": "Unread / manual",
        "Non pris en charge": "Unsupported",
        "Non signée": "Unsigned",
        "Numéro de série": "Serial number",
        "Numéro de série indisponible": "Serial number unavailable",
        "Nécessite une version signée et l’appareil correspondant connecté. Une confirmation sera demandée avant toute écriture.": "Requires a signed version and the matching device to be connected. Confirmation is required before writing to the device.",
        "Options de restauration": "Restore options",
        "Options de restauration refusées.": "Restore options rejected.",
        "Options non canoniques.": "Noncanonical options.",
        "Opération interrompue · résultat non confirmé": "Operation interrupted · result unconfirmed",
        "Opération interrompue · vérifiez l’appareil avant de réessayer": "Operation interrupted · check the device before trying again",
        "Origine de la batterie": "Battery origin",
        "Oui": "Yes",
        "Ouvrez le bundle ReWork complet pour utiliser les sauvegardes.": "Open the complete ReWork app bundle to use backups.",
        "Ouvrez le guide Apple pour connecter le casque et passer en mode récupération.": "Open Apple's guide to connect the headset and enter recovery mode.",
        "Ouvrir": "Open",
        "Ouvrir Apple Configurator": "Open Apple Configurator",
        "Ouvrir le dossier": "Open folder",
        "Par défaut, numéros de série, ECID et adresses réseau sont masqués. Les journaux techniques du moteur peuvent contenir d’autres données.": "Serial numbers, ECIDs and network addresses are hidden by default. Technical engine logs may contain other data.",
        "Pause": "Pause",
        "Personnalisation": "Personalisation",
        "Pièces": "Parts",
        "Pièces et capteurs": "Parts and sensors",
        "Plus tard": "Later",
        "Points à examiner": "Items to review",
        "Pour Vision Pro, utilisez Apple Configurator avec un Developer Strap compatible.": "For Vision Pro, use Apple Configurator with a compatible Developer Strap.",
        "Pourcentage déclaré par l’interface de diagnostic. À comparer avec Réglages > Batterie sur l’appareil.": "Percentage reported by the diagnostic interface. Compare with Settings > Battery on the device.",
        "Poursuivez la configuration sur l’appareil.": "Continue setup on the device.",
        "Progression de la phase en cours : {0} %": "Current phase progress: {0}%",
        "Progression transmise par l’appareil · {0} %": "Progress reported by the device · {0}%",
        "Projet libimobiledevice": "libimobiledevice project",
        "Précédent": "Previous",
        "Préparation de la restauration": "Preparing restore",
        "Préparation de l’opération de sauvegarde": "Preparing backup operation",
        "Préparation du firmware": "Preparing firmware",
        "Prêt dès la connexion": "Ready when connected",
        "Prêt pour un nouveau départ ?": "Ready for a fresh start?",
        "Prêt à préparer la restauration": "Ready to prepare the restore",
        "Publiques": "Public",
        "Que s’est-il passé ? (facultatif)": "What happened? (optional)",
        "Quitter l’aperçu": "Exit preview",
        "Rapport ReWork importé": "Imported ReWork report",
        "Rapport d’incident": "Incident report",
        "Rapport d’incident…": "Incident report…",
        "Rapport exporté": "Report exported",
        "Rapport indisponible.": "Report unavailable.",
        "Rapport…": "Report…",
        "ReWork a quitté de façon inattendue": "ReWork quit unexpectedly",
        "ReWork est une alternative libre et open source pour gérer vos appareils Apple depuis votre Mac. Vérifier, télécharger, restaurer et sauvegarder : les fonctions essentielles, sans abonnement.": "ReWork is a free and open-source alternative for managing your Apple devices from your Mac. Check, download, restore and back up: essential features, without a subscription.",
        "ReWork n’a pas pu interroger le service Apple. Vérifiez si l’appareil apparaît dans le Finder, puis relancez la détection. Vous pouvez joindre un rapport depuis Configuration si le problème persiste.": "ReWork could not query the Apple service. Check whether the device appears in Finder, then retry detection. You can share a report from Settings if the problem persists.",
        "ReWork propose le catalogue visionOS et le téléchargement des IPSW. La restauration du casque se fait avec Apple Configurator et un Developer Strap compatible.": "ReWork provides the visionOS catalogue and IPSW downloads. Headset restoration uses Apple Configurator and a compatible Developer Strap.",
        "ReWork s’appuie sur libimobiledevice, libirecovery et idevicerestore. Les catalogues sont fournis par IPSW.me et AppleDB ; les firmwares sont téléchargés depuis les serveurs Apple.": "ReWork relies on libimobiledevice, libirecovery and idevicerestore. Catalogues are provided by IPSW.me and AppleDB; firmware is downloaded from Apple servers.",
        "ReWork {0} · Open source": "ReWork {0} · Open source",
        "Recherche des firmwares disponibles pour ce modèle.": "Looking up available firmware for this model.",
        "Recherche des modèles iPhone, iPad et Vision Pro disponibles.": "Looking up available iPhone, iPad and Vision Pro models.",
        "Recherche d’un IPSW déjà téléchargé": "Looking for an already downloaded IPSW",
        "Recherche d’un IPSW déjà téléchargé…": "Looking for an already downloaded IPSW…",
        "Rechercher mon appareil": "Find my device",
        "Rechercher un modèle": "Search for a model",
        "Redémarrez l’appareil en mode normal, déverrouillez-le\net acceptez « Faire confiance » pour lancer une vérification.": "Restart the device in normal mode, unlock it\nand accept “Trust” to run a Check.",
        "Relancer la vérification": "Run verification again",
        "Relevé initial": "Initial reading",
        "Relevé initial enregistré. Relancez le Check pour comparer une nouvelle lecture.": "Initial reading saved. Run the Check again to compare a new reading.",
        "Relisez aussi votre description avant de partager. « Envoyer » ouvre le partage macOS : vous choisissez le destinataire et validez l’envoi.": "Review your description before sharing. “Send” opens macOS sharing: choose a recipient and confirm sending.",
        "Remplacer par ce Check": "Replace with this Check",
        "Reprendre": "Resume",
        "Reprenez ici en gardant l’app ouverte.": "Resume here while keeping the app open.",
        "Reprise du suivi de la restauration": "Resuming restore monitoring",
        "Restauration IPSW": "IPSW restore",
        "Restauration bloquée : l’ECID de l’appareil ne peut pas être vérifié.": "Restore blocked: the device ECID cannot be verified.",
        "Restauration des données en cours · gardez l’appareil connecté": "Restoring data · keep the device connected",
        "Restauration d’un iPhone ou d’un iPad en cours": "iPhone or iPad restore in progress",
        "Restauration lancée": "Restore started",
        "Restauration par défaut": "Default restore mode",
        "Restauration terminée": "Restore complete",
        "Restaurer": "Restore",
        "Restaurer Apple Vision Pro": "Restore Apple Vision Pro",
        "Restaurer cette sauvegarde ?": "Restore this backup?",
        "Restaurer les données": "Restore data",
        "Restaurer…": "Restore…",
        "Retrouvez le modèle, le système et les informations accessibles. Lancez un Check, copiez un numéro de série et conservez un relevé pour vos prochaines comparaisons.": "Find the model, system and accessible information. Run a Check, copy a serial number and save a reading for future comparisons.",
        "Revenir": "Back",
        "Revenir à mon appareil": "Back to my device",
        "Revoir la visite guidée": "Replay guided tour",
        "Revoir les prérequis": "Review requirements",
        "Revérifier les outils et la connexion USB de l’appareil": "Recheck tools and the device's USB connection",
        "RÉFÉRENCE": "REFERENCE",
        "RÉSULTAT": "RESULT",
        "Récupération": "Recovery",
        "Réessayer": "Try again",
        "Référence": "Reference",
        "Référence commerciale": "Part number",
        "Référence de comparaison": "Comparison reference",
        "Référence de comparaison enregistrée, sans certification d’origine usine.": "Saved comparison reference, without factory-origin certification.",
        "Référence enregistrée": "Reference saved",
        "Référence importée": "Reference imported",
        "Référence non chargée : ": "Reference not loaded: ",
        "Région commerciale": "Sales region",
        "Réinstallation avec conservation des données": "Reinstalling while keeping user data",
        "Réinstalle iOS en conservant les apps, photos et réglages. Une sauvegarde reste nécessaire : une erreur peut entraîner une perte de données. Aucun effacement automatique en cas d’échec.": "Reinstalls iOS while keeping apps, photos and settings. A backup is still necessary: an error may cause data loss. No automatic erase on failure.",
        "Réinstaller en conservant les données ?": "Reinstall and keep user data?",
        "Réinstaller et conserver": "Reinstall and keep data",
        "Réponse reçue. Chaque champ est validé séparément ; une clé absente reste non exposée.": "Response received. Each field is validated separately; a missing key remains not exposed.",
        "Résultat de la restauration à vérifier": "Restore result needs checking",
        "SN indisponible": "Serial unavailable",
        "Saisissez le code de déverrouillage sur l’appareil": "Enter the passcode on the device",
        "Sauvegarde annulée · données partielles non restaurables": "Backup cancelled · partial data cannot be restored",
        "Sauvegarde d’un appareil": "Backing up a device",
        "Sauvegarde en cours · gardez l’appareil connecté": "Backup in progress · keep the device connected",
        "Sauvegarde restaurée": "Backup restored",
        "Sauvegarde terminée": "Backup complete",
        "Sauvegarder": "Back up",
        "Sauvegarder maintenant": "Back up now",
        "Sauvegardes": "Backups",
        "Sauvegardes locales": "Local backups",
        "Sauvegardez les données et les réglages de votre appareil, avant une restauration ou simplement par précaution.": "Back up your device's data and settings before a restore, or simply as a precaution.",
        "Si le chiffrement est déjà actif sur l’appareil, il reste activé.": "If encryption is already enabled on the device, it stays enabled.",
        "Signaler un problème…": "Report a problem…",
        "Signature Apple : vérifiée par le moteur lors de la restauration.": "Apple signing: checked by the engine during the restore.",
        "Signée": "Signed",
        "Signées uniquement": "Signed only",
        "Sombre": "Dark",
        "Source : ": "Source: ",
        "Sources consultées · {0}": "Sources checked · {0}",
        "Suivant": "Next",
        "Suivez la progression des opérations dans l’app. En cas d’erreur ou d’interruption, vous pouvez consulter puis partager un rapport depuis Configuration. Aucun rapport n’est envoyé automatiquement.": "Track operation progress in the app. If an error or interruption occurs, review and share a report from Settings. No reports are sent automatically.",
        "Suivi de la restauration retrouvé": "Restore monitoring recovered",
        "Sur l’appareil": "On the device",
        "Sur votre Mac": "On your Mac",
        "Suspendre": "Pause",
        "Système": "System",
        "Sécurité": "Security",
        "Sélectionner": "Select",
        "Sélectionnez le modèle correspondant dans la liste.": "Select the matching model from the list.",
        "Sélectionnez un fichier local portant l’extension .ipsw.": "Select a local file with the .ipsw extension.",
        "Sélectionnez une version à télécharger.": "Select a version to download.",
        "Série de la batterie": "Battery serial",
        "Série de la caméra arrière": "Rear camera serial",
        "Série de la caméra avant": "Front camera serial",
        "Série de la caméra infrarouge": "Infrared camera serial",
        "Série de la carte logique": "Logic board serial",
        "Série de l’ultra grand-angle": "Ultra wide camera serial",
        "Série du LiDAR": "LiDAR serial",
        "Série du capteur de lumière": "Light sensor serial",
        "Série du projecteur de points": "Dot projector serial",
        "Série du téléobjectif": "Telephoto camera serial",
        "Série d’écran déclarée": "Reported display serial",
        "Taille non publiée": "Size not published",
        "Test manuel": "Manual test",
        "Testez le déverrouillage biométrique directement sur l’appareil.": "Test biometric unlocking directly on the device.",
        "Testez le déverrouillage biométrique sur l’appareil. Les protocoles publics utilisés ici ne permettent pas de certifier le fonctionnement des capteurs.": "Test biometric unlocking on the device. The public protocols used here cannot certify that the sensors work.",
        "Tout": "All",
        "Tout afficher": "Show all",
        "Tout effacer": "Erase all data",
        "Toutes": "All",
        "Toutes les données de l’appareil seront effacées. Préparez une sauvegarde et gardez le câble branché pendant l’opération.": "All data on the device will be erased. Prepare a backup and keep the cable connected throughout the operation.",
        "Toutes les données seront effacées. La restauration peut échouer si Apple ne signe plus ce firmware. Le verrouillage d’activation restera applicable.": "All data will be erased. The restore may fail if Apple no longer signs this firmware. Activation Lock will still apply.",
        "Téléchargement annulé": "Download cancelled",
        "Téléchargement avant restauration": "Download before restore",
        "Téléchargement de l’IPSW": "Downloading IPSW",
        "Téléchargement depuis Apple": "Downloading from Apple",
        "Téléchargement direct dans {0}.": "Downloads go directly to {0}.",
        "Téléchargement en pause": "Download paused",
        "Téléchargement lancé": "Download started",
        "Téléchargements/ReScope": "Downloads/ReScope",
        "Télécharger": "Download",
        "Télécharger et restaurer": "Download and restore",
        "Téléchargez un IPSW visionOS depuis le catalogue. Pour restaurer le casque, suivez le parcours Apple Configurator.": "Download a visionOS IPSW from the catalogue. To restore the headset, follow the Apple Configurator guide.",
        "USB · local · open source": "USB · local · open source",
        "Un Developer Strap est nécessaire, avec une version compatible M5 pour le casque M5.": "A Developer Strap is required, with an M5-compatible version for the M5 headset.",
        "Un diagnostic qui explique.": "Diagnostics with explanations.",
        "Un fichier compatible sera réutilisé sans téléchargement.": "A compatible file will be reused without downloading.",
        "Un journal de sécurité local permet de retrouver une opération interrompue. Les rapports d’incident restent sur votre Mac jusqu’à votre partage.": "A local safety journal helps recover an interrupted operation. Incident reports stay on your Mac until you share them.",
        "Un outil USB manque dans l’application. Réinstallez le bundle complet de ReWork, puis relancez la détection.": "A USB tool is missing from the app. Reinstall the complete ReWork bundle, then retry detection.",
        "Un projet indépendant, pensé pour une interface soignée, des opérations transparentes et des données qui restent sous votre contrôle. Vous pouvez étudier, modifier et partager le code de ReWork sous licence MIT.": "An independent project with a carefully designed interface, transparent operations and data under your control. You can study, modify and share ReWork's code under the MIT licence.",
        "Un rapport du même appareil a été chargé pour la comparaison. Son origine d’usine n’est pas certifiée.": "A report from the same device has been loaded for comparison. Its factory origin is not certified.",
        "Un rapport local est disponible. Vous pouvez le consulter et le partager.": "A local report is available. You can review and share it.",
        "Un regard clair sur votre appareil": "A clear view of your device",
        "Un regard clair sur votre iPhone et votre iPad.": "A clear view of your iPhone and iPad.",
        "Un état des lieux, sans deviner.": "An overview, without guessing.",
        "Une dernière confirmation précède la réinstallation.": "A final confirmation is required before reinstalling.",
        "Une dernière confirmation précède l’effacement.": "A final confirmation is required before erasing.",
        "Une opération est en cours. Réessayez lorsqu’elle sera terminée.": "An operation is in progress. Try again when it finishes.",
        "Une opération sur l’appareil est déjà en cours.": "A device operation is already in progress.",
        "Une opération sur l’appareil est en cours.": "A device operation is in progress.",
        "Une restauration est déjà active.": "A restore is already active.",
        "Une restauration est déjà en cours. ReWork doit d’abord retrouver son état.": "A restore is already running. ReWork must recover its status first.",
        "Une restauration s’est interrompue. Gardez l’appareil connecté et vérifiez son état avant une nouvelle tentative.": "A restore was interrupted. Keep the device connected and check its status before trying again.",
        "Une sauvegarde locale contient les données prises en charge par iOS. Les contenus déjà synchronisés avec iCloud et certaines apps peuvent nécessiter une connexion après restauration.": "A local backup contains data supported by iOS. Content already synced with iCloud and some apps may require signing in after a restore.",
        "Une valeur lue ne prouve pas l’origine d’une pièce. Une référence absente reste absente : aucun score d’authenticité n’est calculé.": "A reading does not prove a part's origin. An absent reference remains absent: no authenticity score is calculated.",
        "Utiliser ce dossier": "Use this folder",
        "Utiliser comme référence": "Use as reference",
        "VALEUR LUE": "READ VALUE",
        "Valeur lue": "Read value",
        "Valeur lue sur l’appareil. Aucune référence d’usine indépendante n’est disponible.": "Value read from the device. No independent factory reference is available.",
        "Valeurs divergentes": "Conflicting values",
        "Validation de l’appareil et du firmware": "Validating device and firmware",
        "Validation du firmware interrompue": "Firmware validation interrupted",
        "Verrouillage d’activation": "Activation Lock",
        "Verrouillage opérateur": "Carrier lock",
        "Version": "Version",
        "Version iOS": "iOS version",
        "Version iOS / iPadOS": "iOS / iPadOS version",
        "Version illustrative. Aucune vérification de signature effectuée.": "Illustrative version. No signing check performed.",
        "Version indiquée non signée : restauration standard indisponible.": "Version listed as unsigned: standard restore unavailable.",
        "Version indiquée signée dans le catalogue au téléchargement.": "Version listed as signed in the catalogue at download time.",
        "Version non signée : téléchargement possible, restauration standard impossible.": "Unsigned version: can be downloaded, but cannot be restored using the standard process.",
        "Version {0} · build {1} · manifeste et intégrité vérifiés. {2}Aucune restauration lancée.": "Version {0} · build {1} · manifest and integrity verified. {2}No restore started.",
        "Voir la source et les limites du contrôle": "View the source and limitations of this check",
        "Voir mon rapport": "View my report",
        "Vos appareils Apple, à portée de main.": "Your Apple devices, within reach.",
        "Vos appareils. Vos données. Votre liberté.": "Your devices. Your data. Your freedom.",
        "Vos données à l’abri, sur votre Mac.": "Your data, safe on your Mac.",
        "Vos rapports restent sur votre Mac.": "Your reports stay on your Mac.",
        "Vos sauvegardes, sur votre Mac": "Your backups, on your Mac",
        "Vos vérifications, analyses IPSW et restaurations apparaîtront ici.": "Your checks, IPSW inspections and restores will appear here.",
        "Votre IPSW est prêt.": "Your IPSW is ready.",
        "Votre appareil": "Your device",
        "Votre appareil en détail": "Your device in detail",
        "Votre première sauvegarde commence ici": "Your first backup starts here",
        "Vous devez confirmer le mode de restauration et ses conséquences.": "You must confirm the restore mode and its consequences.",
        "Vous pouvez télécharger un firmware avant de connecter votre appareil.": "You can download firmware before connecting your device.",
        "Vue d’ensemble": "Overview",
        "Vue d’ensemble et vérification": "Overview and verification",
        "Vérification": "Verification",
        "Vérification de l’IPSW": "Verifying IPSW",
        "Vérification de l’appareil": "Verifying device",
        "Vérification de l’appareil connecté": "Verifying connected device",
        "Vérification des fichiers locaux": "Checking local files",
        "Vérification du fichier": "Verifying file",
        "Vérification du fichier IPSW": "Verifying IPSW file",
        "Vérification du firmware avant écriture": "Verifying firmware before writing",
        "Vérification du manifeste et du SHA-256": "Verifying manifest and SHA-256",
        "Vérification du système de fichiers": "Verifying file system",
        "Vérification d’un fichier IPSW local": "Inspecting a local IPSW file",
        "Vérification terminée": "Verification complete",
        "Vérifier": "Check",
        "Vérifier l’appareil": "Check device",
        "Vérifiez Localiser dans les réglages et préparez les identifiants Apple du propriétaire avant une restauration.": "Check Find My in Settings and have the owner's Apple account credentials ready before restoring.",
        "Vérifiez Localiser et le compte Apple sur l’appareil. L’app ne peut pas certifier cet état ni supprimer ce verrouillage.": "Check Find My and the Apple account on the device. The app cannot certify this status or remove the lock.",
        "Vérifiez Réglages > Général > Informations > Verrouillage de l’opérateur, puis testez une SIM si nécessaire.": "Check Settings > General > About > Carrier Lock, then test a SIM if needed.",
        "Vérifiez le mode choisi. Une dernière confirmation précède le lancement sur votre appareil.": "Check the selected mode. A final confirmation is required before starting on your device.",
        "Vérifiez l’appareil avant de continuer": "Check the device before continuing",
        "Vérifiez l’appareil dans l’avis d’interruption avant de démarrer une autre opération.": "Check the device in the interruption notice before starting another operation.",
        "Vérifiez votre connexion Internet, puis réessayez.": "Check your internet connection, then try again.",
        "[masqué]": "[hidden]",
        "bêta": "beta",
        "développement": "development",
        "iPhone et iPad": "iPhone and iPad",
        "iPhone ou iPad": "iPhone or iPad",
        "macOS ne voit pas d’iPhone ou d’iPad en USB. Rebranchez-le directement au Mac, écran déverrouillé, puis acceptez « Autoriser la connexion de l’accessoire » sur le Mac si cette demande apparaît. Un câble peut charger sans transmettre de données : essayez un autre câble ou port.": "macOS does not see an iPhone or iPad via USB. Reconnect it directly to the Mac, unlock the screen and allow the accessory connection on the Mac if prompted. A cable can charge without transferring data: try another cable or port.",
        "macOS voit l’appareil, mais ReWork ne peut pas encore lire ses informations. Déverrouillez-le, ouvrez-le dans le Finder et acceptez « Faire confiance » sur l’iPhone et sur le Mac si nécessaire. La détection se relance automatiquement.": "macOS sees the device, but ReWork cannot read its information yet. Unlock it, open it in Finder and accept Trust on the iPhone and Mac if needed. Detection retries automatically.",
        "non signée": "unsigned",
        "signée": "signed",
        "{0} Quittez l’aperçu pour détecter votre appareil USB.": "{0} Exit preview to detect your USB device.",
        "{0} a échoué ({1}). {2}": "{0} failed ({1}). {2}",
        "{0} appareils détectés": "{0} devices detected",
        "{0} données disponibles · {1} contrôles non automatisés.": "{0} available readings · {1} non-automated checks.",
        "{0} n’a pas répondu dans le délai prévu.": "{0} did not respond in time.",
        "{0} point{1} à examiner": "{0} item{1} to review",
        "{0} reçus": "{0} received",
        "{0} {1} · {2} {3} · {4} valeurs de référence": "{0} {1} · {2} {3} · {4} reference values",
        "{0} · manifeste et SHA-256 lus.": "{0} · manifest and SHA-256 read.",
        "{0}/{1} outils disponibles.": "{0}/{1} tools available.",
        "À connecter": "Not connected",
        "À examiner": "Needs review",
        "À installer": "Needs installation",
        "À votre image": "Make it yours",
        "ÉLÉMENT": "ITEM",
        "Écart": "Difference",
        "Échec": "Failed",
        "Échec de restauration": "Restore failed",
        "Échec du téléchargement": "Download failed",
        "Écran": "Display",
        "Écran et caméras": "Display and cameras",
        "Étape de restauration {0}": "Restore step {0}",
        "État": "Status",
        "État de charge déclaré lors de la lecture.": "Charging status reported at the time of reading.",
        "État d’activation": "Activation status",
        "État d’activation lu dans lockdown. Il ne renseigne pas le verrouillage d’activation iCloud.": "Activation status read from lockdown. It does not indicate iCloud Activation Lock status.",
        "État indiqué par le catalogue. Apple vérifie la signature lors d’une restauration.": "Status reported by the catalogue. Apple checks signing during a restore.",
        "Les données transmises à l’outil sont trop volumineuses.": "The data sent to the tool is too large.",
        "Le mot de passe doit compter au plus 255 caractères : lettres sans accents, chiffres, espaces ou ponctuation ASCII.": "The password must be at most 255 characters long: unaccented letters, digits, spaces or ASCII punctuation.",
        "Renommez ce fichier IPSW : son nom ne doit contenir ni *, ni ?, ni crochets, ni barre oblique inverse.": "Rename this IPSW file: its name must not contain *, ?, square brackets or backslashes.",
        "Sans chiffrement, d’autres programmes de votre session macOS peuvent lire cette sauvegarde sans autorisation.": "Without encryption, other programs in your macOS session can read this backup without permission.",
        "Ce mot de passe contient des caractères que le moteur de sauvegarde ne peut pas recevoir (255 caractères ASCII imprimables au plus). Restaurez cette sauvegarde avec le Finder.": "This password contains characters the backup engine cannot receive (at most 255 printable ASCII characters). Restore this backup using Finder.",
        "Connectez votre appareil Apple": "Connect your Apple device",
        "Votre appareil Apple": "Your Apple device",
        "Votre appareil est presque prêt": "Your device is almost ready",
        "Faites confiance à ce Mac": "Trust this Mac",
        "ReWork a besoin d’être réinstallé": "ReWork needs to be reinstalled",
        "La connexion a été interrompue": "The connection was interrupted",
        "Reliez votre appareil à ce Mac et déverrouillez-le. Si un message apparaît, autorisez la connexion pour continuer.": "Connect your device to this Mac and unlock it. If prompted, allow the connection to continue.",
        "Déverrouillez votre appareil et acceptez « Faire confiance » si ce message apparaît. ReWork se connectera automatiquement.": "Unlock your device and choose Trust if prompted. ReWork will connect automatically.",
        "Sur votre appareil, touchez « Faire confiance », puis saisissez votre code. ReWork s’occupe de la suite.": "On your device, tap Trust and enter your passcode. ReWork will take it from there.",
        "Déverrouillez votre appareil pour permettre à ReWork de s’y connecter.": "Unlock your device so ReWork can connect to it.",
        "Un élément nécessaire à la connexion est manquant. Réinstallez ReWork, puis réessayez.": "A component needed to connect is missing. Reinstall ReWork, then try again.",
        "Débranchez votre appareil, puis reconnectez-le à ce Mac. Si le problème persiste, consultez l’aide dans Configuration.": "Disconnect your device, then reconnect it to this Mac. If the issue persists, see Help in Settings.",
        "Vérifiez que votre appareil est connecté et déverrouillé, puis réessayez. Vous pouvez aussi essayer un autre câble ou un autre port.": "Make sure your device is connected and unlocked, then try again. You can also try a different cable or port.",
        "Faites connaissance avec ReWork. Retrouvez vos appareils Apple, prenez soin de vos données et découvrez les possibilités qui s’offrent à vous.": "Get to know ReWork. Explore your Apple devices, take care of your data and discover what you can do.",
        "Conserver les données de l’appareil": "Keep device data",
        "Choisissez la version du système à installer, ou utilisez un fichier déjà téléchargé.": "Choose the system version to install, or use a file you’ve already downloaded.",
        "L’empreinte du fichier ne correspond pas au catalogue. Le téléchargement a été supprimé.": "The file’s fingerprint does not match the catalogue. The download was deleted.",
        "Le fichier IPSW est endommagé ou incomplet. Le téléchargement a été supprimé.": "The IPSW file is damaged or incomplete. The download was deleted.",
        "De {0} vers {1}": "From {0} to {1}",
        "l’appareil sélectionné": "the selected device",
        "{0} bêta {1}": "{0} beta {1}",
        "{0} bêta": "{0} beta",
        "Niveau de charge non exposé": "Charge level not reported",
        "Niveau de charge {0} %, en charge": "Charge level {0}%, charging",
        "Niveau de charge {0} %": "Charge level {0}%",
        "En charge": "Charging",
        "Chargée, sur secteur": "Charged, on power",
        "Sur secteur, sans recharge": "On power, not charging",
        "Sur batterie": "On battery",
        "{0} sur {1} de conception": "{0} of {1} design capacity",
        "{0} cycles de charge": "{0} charge cycles",
        "Capacité": "Capacity",
        "Alimentation": "Power",
        "Aperçu de l’écran verrouillé fourni par l’appareil. L’heure et la date sont celles de cet aperçu.": "Lock screen preview provided by the device. The time and date belong to that preview.",
        "Test Face ID": "Face ID test",
        "Vérifiez le déverrouillage et consultez les informations disponibles sur TrueDepth.": "Check unlocking and view the available TrueDepth information.",
        "Fermer le test Face ID": "Close Face ID test",
        "Aperçu : ce test utilise un appareil fictif.": "Preview: this test uses a fictional device.",
        "Le résultat de déverrouillage est confirmé par vous. ReWork ne déclenche pas Face ID depuis le Mac et ne recueille aucune donnée de votre visage.": "You confirm the unlock result. ReWork does not trigger Face ID from your Mac or collect any data about your face.",
        "Vérifiez Face ID sur votre appareil": "Check Face ID on your device",
        "Regardez l’écran de votre appareil": "Look at your device’s screen",
        "Si le code est demandé, saisissez-le une fois avant de commencer.": "If asked for your passcode, enter it once before you begin.",
        "Verrouillez l’appareil avec le bouton latéral, puis réveillez l’écran.": "Lock your device with the side button, then wake the screen.",
        "Regardez l’écran. Le cadenas doit s’ouvrir sans saisir votre code.": "Look at the screen. The padlock should open without entering your passcode.",
        "Le cadenas s’est-il ouvert avec Face ID ?": "Did the padlock open with Face ID?",
        "Pour un iPhone ou un iPad équipé de Face ID.": "For an iPhone or iPad equipped with Face ID.",
        "Résultat confirmé par vous": "Result confirmed by you",
        "Vérifiez Réglages > Face ID et code sur l’appareil pour configurer Face ID ou activer le déverrouillage.": "Check Settings > Face ID & Passcode on your device to set up Face ID or enable unlocking.",
        "Vérifiez que la caméra TrueDepth est dégagée et que Face ID est activé pour le déverrouillage. Un code demandé ne signifie pas forcément une panne.": "Make sure the TrueDepth camera is clear and Face ID is enabled for unlocking. Being asked for a passcode does not necessarily mean there is a fault.",
        "Identification du visage": "Face recognition",
        "Un identifiant lu indique que l’appareil communique cette information. Il ne certifie pas le fonctionnement du composant. Le capteur de proximité n’est pas évalué par ce test.": "A reported identifier means the device provides that information. It does not confirm that the component works. This test does not assess the proximity sensor.",
        "Identifiant lu": "Identifier read",
        "Déverrouillage réussi": "Unlock successful",
        "Déverrouillage non réussi": "Unlock unsuccessful",
        "Face ID non configuré ou indisponible": "Face ID not configured or unavailable",
        "Test non effectué": "Test not performed",
        "Non, le cadenas reste fermé": "No, the padlock stays closed",
        "Oui, Face ID m’a reconnu": "Yes, Face ID recognised me",
        "Face ID n’est pas configuré": "Face ID is not configured",
        "Commencer le test": "Start test",
        "Recommencer": "Try again",
        "Caméra infrarouge": "Infrared camera",
        "Projecteur de points": "Dot projector",
        "Capteur de proximité": "Proximity sensor",
        "Moins d’interruptions pendant la restauration": "Fewer interruptions during restoration",
        "L’appareil se reconnecte plusieurs fois. macOS peut demander son autorisation à chaque étape.": "Your device reconnects several times. macOS may ask for permission at each stage.",
        "Configurer les connexions sur ce Mac": "Set up connections on this Mac",
        "Dans Réglages Système > Confidentialité et sécurité > Accessoires, choisissez « Autoriser automatiquement au déverrouillage », puis gardez votre Mac déverrouillé.": "In System Settings > Privacy & Security > Accessories, choose ‘Automatically Allow When Unlocked’, then keep your Mac unlocked.",
        "Ce réglage concerne tous les accessoires connectés à ce Mac. ReWork ne le modifie pas.": "This setting applies to all accessories connected to this Mac. ReWork does not change it.",
        "Ouvrir les réglages macOS": "Open macOS settings",
        "Si macOS demande d’autoriser l’appareil, cliquez sur « Autoriser » et gardez le câble branché.": "If macOS asks to allow your device to connect, click ‘Allow’ and keep the cable connected.",
        "Votre appareil peut encore redémarrer. Gardez-le connecté le temps qu’il réapparaisse dans ReWork.": "Your device may still be restarting. Keep it connected until it reappears in ReWork.",
        "Installation du système terminée": "System installation complete",
        "La fin de l’installation est confirmée. L’appareil peut encore terminer son démarrage.": "Installation is confirmed complete. Your device may still be finishing startup.",
        "L’appareil peut encore terminer son démarrage. Gardez-le connecté jusqu’à l’écran d’accueil ou de configuration.": "Your device may still be finishing startup. Keep it connected until the Home Screen or setup screen appears.",
        "Le moteur n’a pas confirmé la fin de l’installation. Gardez l’appareil connecté et vérifiez son état avant une nouvelle tentative.": "The engine did not confirm installation was complete. Keep your device connected and check its state before trying again.",
        "Bienvenue dans iTelier": "Welcome to iTelier",
        "Ce fichier ne contient pas de référence iTelier valide et exploitable.": "This file does not contain a valid usable iTelier reference.",
        "Ce rapport reste sur votre Mac. Il contient la version de iTelier, macOS, le modèle d’appareil et l’étape concernée. Les identifiants, chemins et journaux bruts sont exclus.": "This report stays on your Mac. It contains the iTelier version, macOS version, device model and relevant step. Identifiers, paths and raw logs are excluded.",
        "Choisissez le thème sombre, clair ou système et votre langue dans Configuration. iTelier est un projet libre, sans abonnement, conçu pour vous laisser la main sur vos appareils. Cette visite reste accessible dans les réglages.": "Choose dark, light or system appearance and your language in Settings. iTelier is a free project without a subscription, designed to keep you in control of your devices. You can replay this tour in Settings.",
        "Choisissez votre firmware dans le catalogue. iTelier vérifie les IPSW déjà présents, télécharge depuis Apple et permet de mettre le téléchargement en pause. Choisissez ensuite de conserver les données ou d’effacer l’appareil avant confirmation.": "Choose firmware from the catalogue. iTelier checks existing IPSWs, downloads from Apple and lets you pause downloads. Then choose to keep data or erase the device before confirming.",
        "Connectez votre iPhone ou iPad avec un câble USB, déverrouillez-le et acceptez Faire confiance. Découvrez les fonctions de iTelier en quelques étapes.": "Connect your iPhone or iPad using a USB cable, unlock it and accept Trust. Discover iTelier in a few steps.",
        "Consultation de iTelier": "Browsing iTelier",
        "Gardez iTelier ouvert et l’appareil connecté jusqu’à la fin de l’opération.": "Keep iTelier open and the device connected until the operation finishes.",
        "Importer un rapport iTelier comme référence": "Import a iTelier report as a reference",
        "Infos · À propos de iTelier": "Info · About iTelier",
        "La restauration directe et la sauvegarde locale de Vision Pro ne sont pas prises en charge par iTelier. Ne comptez pas sur une conservation des données lors de cette procédure.": "Direct Vision Pro restoration and local backups are not supported by iTelier. Do not rely on data preservation during this procedure.",
        "Le module de protection de la restauration est absent. Lancez le bundle iTelier complet.": "The restore protection module is missing. Launch the complete iTelier app bundle.",
        "Les outils de détection USB, de diagnostic et de restauration IPSW sont inclus dans iTelier.": "USB detection, diagnostics and IPSW restore tools are included in iTelier.",
        "Les outils intégrés et les illustrations Apple conservent leurs licences et droits respectifs. iTelier n’est pas affilié à Apple.": "Bundled tools and Apple illustrations retain their respective licences and rights. iTelier is not affiliated with Apple.",
        "L’activation s’applique aux prochaines sauvegardes de cet appareil. Conservez ce mot de passe : iTelier ne l’enregistre pas et ne pourra pas le retrouver.": "Enabling encryption applies to future backups of this device. Keep this password: iTelier does not store it and cannot recover it.",
        "L’outil de lecture est absent du bundle. Réinstallez iTelier.": "The reading tool is missing from the bundle. Reinstall iTelier.",
        "Ouvrez le bundle iTelier complet pour utiliser les sauvegardes.": "Open the complete iTelier app bundle to use backups.",
        "Rapport iTelier importé": "Imported iTelier report",
        "iTelier a quitté de façon inattendue": "iTelier quit unexpectedly",
        "iTelier est une alternative libre et open source pour gérer vos appareils Apple depuis votre Mac. Vérifier, télécharger, restaurer et sauvegarder : les fonctions essentielles, sans abonnement.": "iTelier is a free and open-source alternative for managing your Apple devices from your Mac. Check, download, restore and back up: essential features, without a subscription.",
        "iTelier n’a pas pu interroger le service Apple. Vérifiez si l’appareil apparaît dans le Finder, puis relancez la détection. Vous pouvez joindre un rapport depuis Configuration si le problème persiste.": "iTelier could not query the Apple service. Check whether the device appears in Finder, then retry detection. You can share a report from Settings if the problem persists.",
        "iTelier propose le catalogue visionOS et le téléchargement des IPSW. La restauration du casque se fait avec Apple Configurator et un Developer Strap compatible.": "iTelier provides the visionOS catalogue and IPSW downloads. Headset restoration uses Apple Configurator and a compatible Developer Strap.",
        "iTelier s’appuie sur libimobiledevice, libirecovery et idevicerestore. Les catalogues sont fournis par IPSW.me et AppleDB ; les firmwares sont téléchargés depuis les serveurs Apple.": "iTelier relies on libimobiledevice, libirecovery and idevicerestore. Catalogues are provided by IPSW.me and AppleDB; firmware is downloaded from Apple servers.",
        "iTelier {0} · Open source": "iTelier {0} · Open source",
        "Un outil USB manque dans l’application. Réinstallez le bundle complet de iTelier, puis relancez la détection.": "A USB tool is missing from the app. Reinstall the complete iTelier bundle, then retry detection.",
        "Un projet indépendant, pensé pour une interface soignée, des opérations transparentes et des données qui restent sous votre contrôle. Vous pouvez étudier, modifier et partager le code de iTelier sous licence MIT.": "An independent project with a carefully designed interface, transparent operations and data under your control. You can study, modify and share iTelier's code under the MIT licence.",
        "Une restauration est déjà en cours. iTelier doit d’abord retrouver son état.": "A restore is already running. iTelier must recover its status first.",
        "macOS voit l’appareil, mais iTelier ne peut pas encore lire ses informations. Déverrouillez-le, ouvrez-le dans le Finder et acceptez « Faire confiance » sur l’iPhone et sur le Mac si nécessaire. La détection se relance automatiquement.": "macOS sees the device, but iTelier cannot read its information yet. Unlock it, open it in Finder and accept Trust on the iPhone and Mac if needed. Detection retries automatically.",
        "iTelier a besoin d’être réinstallé": "iTelier needs to be reinstalled",
        "Déverrouillez votre appareil et acceptez « Faire confiance » si ce message apparaît. iTelier se connectera automatiquement.": "Unlock your device and choose Trust if prompted. iTelier will connect automatically.",
        "Sur votre appareil, touchez « Faire confiance », puis saisissez votre code. iTelier s’occupe de la suite.": "On your device, tap Trust and enter your passcode. iTelier will take it from there.",
        "Déverrouillez votre appareil pour permettre à iTelier de s’y connecter.": "Unlock your device so iTelier can connect to it.",
        "Un élément nécessaire à la connexion est manquant. Réinstallez iTelier, puis réessayez.": "A component needed to connect is missing. Reinstall iTelier, then try again.",
        "Faites connaissance avec iTelier. Retrouvez vos appareils Apple, prenez soin de vos données et découvrez les possibilités qui s’offrent à vous.": "Get to know iTelier. Explore your Apple devices, take care of your data and discover what you can do.",
        "Le résultat de déverrouillage est confirmé par vous. iTelier ne déclenche pas Face ID depuis le Mac et ne recueille aucune donnée de votre visage.": "You confirm the unlock result. iTelier does not trigger Face ID from your Mac or collect any data about your face.",
        "Ce réglage concerne tous les accessoires connectés à ce Mac. iTelier ne le modifie pas.": "This setting applies to all accessories connected to this Mac. iTelier does not change it.",
        "Votre appareil peut encore redémarrer. Gardez-le connecté le temps qu’il réapparaisse dans iTelier.": "Your device may still be restarting. Keep it connected until it reappears in iTelier.",
        "Ce rapport reste sur votre Mac. Il contient la version d’iTelier, macOS, le modèle d’appareil et l’étape concernée. Les identifiants, chemins et journaux bruts sont exclus.": "This report stays on your Mac. It contains the iTelier version, macOS version, device model and relevant step. Identifiers, paths and raw logs are excluded.",
        "Connectez votre iPhone ou iPad avec un câble USB, déverrouillez-le et acceptez Faire confiance. Découvrez les fonctions d’iTelier en quelques étapes.": "Connect your iPhone or iPad using a USB cable, unlock it and accept Trust. Discover iTelier in a few steps.",
        "Consultation d’iTelier": "Browsing iTelier",
        "Infos · À propos d’iTelier": "Info · About iTelier",
        "Un outil USB manque dans l’application. Réinstallez le bundle complet d’iTelier, puis relancez la détection.": "A USB tool is missing from the app. Reinstall the complete iTelier bundle, then retry detection.",
        "Un projet indépendant, pensé pour une interface soignée, des opérations transparentes et des données qui restent sous votre contrôle. Vous pouvez étudier, modifier et partager le code d’iTelier sous licence MIT.": "An independent project with a carefully designed interface, transparent operations and data under your control. You can study, modify and share iTelier's code under the MIT licence.",
    ]
}
